Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.boot_timeout = 600

  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 5173, host: 5173

  config.vm.synced_folder "./backend", "/home/vagrant/backend"
  config.vm.synced_folder "./frontend", "/home/vagrant/frontend"

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "/vagrant/playbook.yml"
    ansible.inventory_path = "/vagrant/inventory.ini"
    ansible.compatibility_mode = "2.0"  # <--- KLUCZOWE!
    ansible.become = true 
  end
end
