spring:
  application:
    name: studentapp
  datasource:
    url: jdbc:postgresql://localhost:5432/studentdb
    username: postgres
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
